[project]
name = "wallcontroller-buttons-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bottle>=0.13.3",
    "netifaces>=0.11.0",
]
